# Generated by Django 3.2.8 on 2021-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oniet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawDataView',
        ),
    ]
