# Generated by Django 3.2.8 on 2021-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oniet', '0002_delete_rawdataview'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_renap', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('accesoAgua', models.CharField(max_length=150)),
                ('accesoElectricidad', models.CharField(max_length=150)),
                ('accesoCloaca', models.CharField(max_length=150)),
                ('cantFamilias', models.IntegerField()),
            ],
        ),
    ]
